### ISSUE TITLE
IOS问题

### ISSUE THREAD

**Issue by 743306400** [lurongshuang/ali_auth_person#1]
大佬,IOS点击实名认证的时候出现网络错误,怎么解决呀?

**Comment by lurongshuang** [comment]
返回的code错误，阿里那边有对应的吗

**Comment by lurongshuang** [comment]
https://help.aliyun.com/document_detail/163106.html

**Comment by lurongshuang** [comment]
看一下，里面的具体配置，有没有操作：
https://help.aliyun.com/document_detail/163106.html
