### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by 731751218** [lurongshuang/ali_auth_person#2]
打包报这个错怎么解决？

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':ali_auth_person:compileReleaseJavaWithJavac'.
> Could not resolve all files for configuration ':ali_auth_person:releaseCompileClasspath'.
   > Failed to transform flutter.jar to match attributes {artifactType=android-classes-jar, org.gradle.libraryelements=jar, org.gradle.usage=java-runtime}.
      > Execution failed for JetifyTransform: /Users/moac/Applications/flutter/bin/cache/artifacts/engine/android-arm/flutter.jar.
         > Transform's input file does not exist: /Users/moac/Applications/flutter/bin/cache/artifacts/engine/android-arm/flutter.jar. (See https://issuetracker.google.com/issues/158753935)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 8s

**Comment by lurongshuang** [comment]
是不是 gradle版本的问题？

**Comment by lurongshuang** [comment]
https://help.aliyun.com/document_detail/127598.html

**Comment by lurongshuang** [comment]
我的版本：
 ext.kotlin_version = '1.6.10'
 
 
   classpath 'com.android.tools:r8:2.1.67'
        classpath 'com.android.tools.build:gradle:4.1.3'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        
        
        
        
        distributionUrl=https://services.gradle.org/distributions/gradle-6.7-all.zip

**Comment by lurongshuang** [comment]
是不是 gradle版本的问题？

https://help.aliyun.com/document_detail/127598.html


我的版本：
ext.kotlin_version = '1.6.10'

classpath 'com.android.tools:r8:2.1.67'
classpath 'com.android.tools.build:gradle:4.1.3'
classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"

    distributionUrl=https://services.gradle.org/distributions/gradle-6.7-all.zip
