### ISSUE TITLE
大佬求助

### ISSUE THREAD

**Issue by zhujiahong** [lurongshuang/ali_auth_person#3]
大佬 我在ios端 SDK调用了以后没有ui元素 拍照功能都正常 就是没有那些ui图标 不知道是哪里出了问题

**Comment by lurongshuang** [comment]
![截屏2022-09-06 18 57 29的副本](https://user-images.githubusercontent.com/20178753/188618278-8b45e1d9-b2ae-4a5d-9b99-97ae85cd4962.png)

**Comment by lurongshuang** [comment]
将资源bundle 导入到项目或者库下即可
