### ISSUE TITLE
求助，急！！！

### ISSUE THREAD

**Issue by ConClude7** [lurongshuang/ali_auth_person#4]
亲爱的作者，我在尝试使用此插件时遇到了问题。

`
ali_auth_person:
    git:
      url: https://github.com/lurongshuang/ali_auth_person.git`
`

以下是我Flutter Doctor运行结果:
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.3.7, on Microsoft Windows [版本 10.0.19044.2251], locale zh-CN)
[!] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[X] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[√] Android Studio (version 2021.3)
[√] Connected device (3 available)
[!] HTTP Host Availability
    X HTTP host "https://storage.fluter.io.cn" is not reachable. Reason: An error occurred while checking the HTTP host:
      Failed host lookup: 'storage.fluter.io.cn'
`

Flutter version:
Flutter 3.3.7 • channel stable • https://github.com/flutter/flutter.git
Framework • revision e99c9c7cd9 (11 days ago) • 2022-11-01 16:59:00 -0700
Engine • revision 857bd6b74c
Tools • Dart 2.18.4 • DevTools 2.15.0

运行结果:
`
One or more plugins require a higher Android SDK version.
Fix this issue by adding the following to E:\APP\Flutter\android\app\build.gradle:
android {
  compileSdkVersion 33
  ...
}

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':ali_auth_person:generateDebugRFile'.
> Could not resolve all files for configuration ':ali_auth_person:debugCompileClasspath'.
   > Could not resolve io.flutter:flutter_embedding_debug:1.0.0-857bd6b74c5eb56151bfafe91e7fa6a82b6fee25.
     Required by:
         project :ali_auth_person
      > Could not resolve io.flutter:flutter_embedding_debug:1.0.0-857bd6b74c5eb56151bfafe91e7fa6a82b6fee25.
         > Could not get resource 'https://storage.fluter.io.cn/download.flutter.io/io/flutter/flutter_embedding_debug/1.0.0-857bd6b74c5eb56151bfafe91e7fa6a82b6fee25/flutter_embedding_debug-1.0.0-857bd6b74c5eb56151bfafe91e7fa6a82b6fee25.pom'.
            > Could not GET 'https://storage.fluter.io.cn/download.flutter.io/io/flutter/flutter_embedding_debug/1.0.0-857bd6b74c5eb56151bfafe91e7fa6a82b6fee25/flutter_embedding_debug-1.0.0-857bd6b74c5eb56151bfafe91e7fa6a82b6fee25.pom'.
               > ��֪�������������� (storage.fluter.io.cn)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 29s
`

当我在对应的build.gradle中修改compileSdkVersion为33后会遇到下面的错误:

`
Warning: Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns http://schemas.android.com/repository/android/common/01
Warning: Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/03 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/03 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/03 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':ali_auth_person:generateDebugRFile'.
> Could not resolve all files for configuration ':ali_auth_person:debugCompileClasspath'.
   > Could not resolve io.flutter:flutter_embedding_debug:1.0.0-857bd6b74c5eb56151bfafe91e7fa6a82b6fee25.
     Required by:
         project :ali_auth_person
      > Could not resolve io.flutter:flutter_embedding_debug:1.0.0-857bd6b74c5eb56151bfafe91e7fa6a82b6fee25.
         > Could not get resource 'https://storage.fluter.io.cn/download.flutter.io/io/flutter/flutter_embedding_debug/1.0.0-857bd6b74c5eb56151bfafe91e7fa6a82b6fee25/flutter_embedding_debug-1.0.0-857bd6b74c5eb56151bfafe91e7fa6a82b6fee25.pom'.
            > Could not GET 'https://storage.fluter.io.cn/download.flutter.io/io/flutter/flutter_embedding_debug/1.0.0-857bd6b74c5eb56151bfafe91e7fa6a82b6fee25/flutter_embedding_debug-1.0.0-857bd6b74c5eb56151bfafe91e7fa6a82b6fee25.pom'.
               > ��֪�������������� (storage.fluter.io.cn)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 30s
`
我该怎么做？谢谢！

**Comment by lurongshuang** [comment]
你的代理没有问题吧？

**Comment by lurongshuang** [comment]
微信L2212709787
